# Generated by Django 5.1.4 on 2026-09-18 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد')),
                ('currency', models.CharField(choices=[('YE', 'ريال يمني')], default='YE', max_length=3, verbose_name='العملة')),
                ('is_locked', models.BooleanField(default=False, verbose_name='محظورة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transfer_code', models.CharField(max_length=10, unique=True, verbose_name='رمز التحويل')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='Transaction.wallet', verbose_name='محفظة المرسل')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='Transaction.wallet', verbose_name='محفظة المستقبل')),
            ],
            options={
                'verbose_name': 'تحويل مالي',
                'verbose_name_plural': 'التحويلات المالية',
                'indexes': [models.Index(fields=['transfer_code'], name='Transaction_transfe_e75d71_idx'), models.Index(fields=['status'], name='Transaction_status_df48e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('transaction_type', models.CharField(choices=[('charge', 'شحن'), ('transfer', 'تحويل'), ('withdraw', 'سحب'), ('payment', 'دفع'), ('refund', 'استرداد')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم المرجع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Transaction.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'عملية',
                'verbose_name_plural': 'العمليات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type'], name='Transaction_transac_422b11_idx'), models.Index(fields=['status'], name='Transaction_status_86cabb_idx')],
            },
        ),
    ]
