# Generated by Django 5.1.4 on 2026-09-18 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري')),
                ('duration_days', models.IntegerField(help_text='عدد أيام سريان الاشتراك', verbose_name='المدة بالأيام')),
                ('max_trips', models.IntegerField(blank=True, help_text='إذا كان غير محدد، عدد الرحلات غير محدود', null=True, verbose_name='الحد الأقصى للرحلات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('participants', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='يجب أن يُدخل رقم هاتف صالح.', regex='^\\+?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف الجهاز')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('status_del', models.BooleanField(default=False, verbose_name='محذوف')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='CasheItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('from_location', models.CharField(max_length=255, verbose_name='من')),
                ('to_location', models.CharField(max_length=255, verbose_name='إلى')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='اسم المستلم')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='هاتف المستلم')),
                ('item_description', models.TextField(verbose_name='وصف الشحنة')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الوزن (كجم)')),
                ('urgent', models.BooleanField(default=False, verbose_name='عاجل')),
                ('insurance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ التأمين')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('in_progress', 'قيد التوصيل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashe_deliveries', to='apis.client', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب توصيل مسبق',
                'verbose_name_plural': 'طلبات التوصيل المسبقة',
            },
        ),
        migrations.CreateModel(
            name='CasheBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255, verbose_name='من')),
                ('to_location', models.CharField(max_length=255, verbose_name='إلى')),
                ('departure_time', models.DateTimeField(verbose_name='وقت المغادرة')),
                ('passengers', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الركاب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('failed', 'فشل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashe_bookings', to='apis.client', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حجز مسبق',
                'verbose_name_plural': 'الحجوزات المسبقة',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='يجب أن يُدخل رقم هاتف صالح.', regex='^\\+?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('where_location', models.CharField(max_length=255, verbose_name='وين')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الرخصة')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='التقييم')),
                ('total_trips', models.IntegerField(default=0, verbose_name='إجمالي الرحلات')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح للرحلات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقون',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content', models.TextField(blank=True, null=True, verbose_name='المحتوى')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'pdf', 'mp3', 'mp4'])])),
                ('is_read', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apis.chat', verbose_name='المحادثة')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apis.message'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('remaining_trips', models.IntegerField(blank=True, null=True, verbose_name='الرحلات المتبقية')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='apis.driver', verbose_name='السائق')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subscriptionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المتابعة'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='open', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='apis.driver', verbose_name='مُعيّن إلى')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255, verbose_name='من')),
                ('to_location', models.CharField(max_length=255, verbose_name='إلى')),
                ('departure_time', models.DateTimeField(verbose_name='وقت المغادرة')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='المدة المتوقعة')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المسافة (كم)')),
                ('available_seats', models.IntegerField(default=0, verbose_name='عدد المقاعد المتاحة')),
                ('price_per_seat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر لكل مقعد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('full', 'مكتملة'), ('completed', 'منتهية'), ('cancelled', 'ملغية')], default='pending', max_length=20, verbose_name='الحالة')),
                ('route_coordinates', models.TextField(blank=True, help_text='تنسيق JSON لإحداثيات المسار (خط الطول والعرض)', null=True, verbose_name='إحداثيات المسار')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='apis.driver', verbose_name='السائق')),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'الرحلات',
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='تعليق')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apis.driver', verbose_name='السائق')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.client', verbose_name='المقيّم')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
        migrations.CreateModel(
            name='ItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='اسم المستلم')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='هاتف المستلم')),
                ('item_description', models.TextField(verbose_name='وصف الشحنة')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الوزن (كجم)')),
                ('insurance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ التأمين')),
                ('delivery_code', models.CharField(max_length=10, verbose_name='كود الشحنة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_transit', 'قيد النقل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.JSONField(default=list, help_text='قائمة بأرقام/أسماء المقاعد المحددة', verbose_name='المقاعد المحجوزة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.client', verbose_name='العميل')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.IntegerField()),
                ('total_bookings', models.IntegerField()),
                ('total_deliveries', models.IntegerField()),
                ('passengers_count', models.IntegerField()),
                ('total_weight', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('order', models.PositiveIntegerField(verbose_name='ترتيب المحطة')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الوصول المتوقع')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'محطة توقف',
                'verbose_name_plural': 'محطات التوقف',
                'db_table': 'trip_stops',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('plate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم اللوحة')),
                ('color', models.CharField(max_length=30, verbose_name='اللون')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='السعة')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'سيدان'), ('suv', 'SUV'), ('van', 'فان'), ('truck', 'شاحنة')], default='sedan', max_length=20, verbose_name='نوع المركبة')),
                ('manufacture_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الصنع')),
                ('inspection_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء الفحص الفني')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
                'db_table': 'vehicles',
                'indexes': [models.Index(fields=['vehicle_type'], name='vehicles_vehicle_d54349_idx'), models.Index(fields=['plate_number'], name='vehicles_plate_n_de64b1_idx')],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='apis.vehicle', verbose_name='المركبة'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicles',
            field=models.ManyToManyField(related_name='drivers', to='apis.vehicle', verbose_name='المركبات'),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('reason', models.CharField(choices=[('referral', 'مكافأة إحالة'), ('promotion', 'عرض ترويجي'), ('other', 'أخرى')], default='other', max_length=255, verbose_name='السبب')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('processed', models.BooleanField(default=False, verbose_name='معالجة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
                'indexes': [models.Index(fields=['expiration_date'], name='apis_bonus_expirat_440be0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['city'], name='clients_city_c00b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_status_98ee60_idx'),
        ),
        migrations.AddIndex(
            model_name='casheitemdelivery',
            index=models.Index(fields=['urgent'], name='apis_cashei_urgent_6b709c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashebooking',
            index=models.Index(fields=['departure_time'], name='apis_casheb_departu_485e03_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['updated_at'], name='apis_chat_updated_256b25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('id',)},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='apis_subscr_end_dat_877d32_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_active'], name='apis_subscr_is_acti_fc1abd_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='apis_suppor_status_ed031d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority'], name='apis_suppor_priorit_0abcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating'], name='apis_rating_rating_e3b123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('trip', 'rated_by')},
        ),
        migrations.AddIndex(
            model_name='itemdelivery',
            index=models.Index(fields=['delivery_code'], name='apis_itemde_deliver_84d245_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdelivery',
            index=models.Index(fields=['status'], name='apis_itemde_status_369bca_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='apis_bookin_status_c52b97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripstop',
            unique_together={('trip', 'order')},
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_time'], name='apis_trip_departu_6dd7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='apis_trip_status_e536e0_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['rating'], name='apis_driver_rating_b68803_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_available'], name='apis_driver_is_avai_faafb8_idx'),
        ),
    ]
